name: PR - Lint and Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint and test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    permissions:
      contents: read # required to checkout code
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install
          poetry run pip list

      - name: Poetry check
        run: |
          poetry check --lock

      - name: Lint with ruff
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1

      - name: Lint with pylint
        run: |
          poetry run pylint --disable=W,C,R,E -j 0 -rn -sn py_powershell/

      - name: Bandit
        run: |
          poetry run bandit -q -lll -x './tests' -r .

      - name: Safety
        run: |
          poetry run safety check --ignore 70612 --ignore 84031 --ignore 82331 --ignore 82332 --ignore 83159 --ignore 82754 --ignore 84183 --ignore 84339 --ignore 81132 --ignore 80401 --ignore 79756

      - name: Vulture
        run: |
          poetry run vulture --min-confidence 100 .

      - name: Test with pytest
        run: |
          poetry run pytest -n auto --cov=./py_powershell --cov-report=xml tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: prowler-cloud/py-pwsh-session
